### ISSUE TITLE
abind error

### ISSUE THREAD

**Issue by adw96** [bryandmartin/MicrobiomePack#8]
A couple of issues with X matrices of rank 2

setwd("/Users/adwillis/software/MicrobiomePack/")
build("/Users/adwillis/software/MicrobiomePack/")
install(pkg = "/Users/adwillis/software/MicrobiomePack/")
library(MicrobiomePack)

set.seed(1)
n <- 20
q <- 4
p <- 1
mmm <- 1e6
mm <- rep(x=mmm, n)

beta <- matrix(0, nrow=p, ncol=q) # p x q
Sigma <- diag(rep(1, q)) # q x q
my_x <- matrix(1, nrow=n, ncol=p) # n x p
mu <- my_x %*% beta # n x q

Y <- matrix(NA, nrow=n, ncol=q)
for (i in 1:n) {
  Y[i, ] <- MASS::mvrnorm(n=1, mu=mu[i, ], Sigma=Sigma)
}
exp_Y <- exp(Y)
denominators <- exp_Y %>% apply(1, sum) %>% add(1)
compositions <- cbind(exp_Y, 1) / denominators # n x (q+1)
my_w <- matrix(NA, nrow=n, ncol=q+1)
for (i in 1:n) {
  my_w[i, ] <- rmultinom(n=1, size=mm[i], prob=compositions[i,])
}
my_w

### Working
x1 <- cbind(1, rnorm(20), rnorm(20))
MicrobiomePack::LNM.EM(my_w, x1, 1)

### Not working
x2 <- cbind(1, rnorm(20))
MicrobiomePack::LNM.EM(my_w, x2, 1)

### Not working, should be the same
x3 <- cbind(1, rep(c(0,1), each = 10))
x4 <- cbind(1, rep(c(1,0), each = 10))
MicrobiomePack::LNM.EM(my_w, x3, 1)
MicrobiomePack::LNM.EM(my_w, x4, 1)

**Comment by bryandmartin** [comment]
Try now, and let me know if it fixed the issue.

**Comment by adw96** [comment]
Wonderful, thanks!
